site_name: Open Science Text Analysis
repo_url: https://github.com/andreigrozescu/open-science-ai-rse
theme:
  name: mkdocs

nav:
  - Home: docs/index.md
  - Installation: docs/installation.md
  - Usage: docs/usage.md
  - Scripts: docs/scripts.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

