site_name: Open Science Text Analysis
repo_url: https://github.com/andreigrozescu/open-science-ai-rse
theme:
  name: mkdocs

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Scripts: scripts.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

