site_name: Open Science Text Analysis
repo_url: https://github.com/andreigrozescu/open-science-ai-rse
theme:
  name: material

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference: api.md
  - About: about.md
